source 'https://rubygems.org'
gem 'sinatra'
gem 'activerecord', :require => 'active_record'
gem 'sinatra-activerecord', :require => 'sinatra/activerecord'
gem 'rake'
gem 'sqlite3'
gem 'require_all'
gem 'thin'
gem 'shotgun'
gem 'pg'
gem 'pry'
gem 'tux'
gem 'rack-flash3'
gem 'sinatra-flash'
