development:
        adapter:        sqlite3
        database:       db/recipes.db
        pool:   2

production: 
        adapter:        postgresql
        encoding:       unicode
        pool:   5
        host:   <%= ENV['DATABASE_HOST'] %>
        database:       <%= ENV['DATABASE_NAME'] %>
        username:       <%= ENV['DATABASE_USER'] %>
        password:       <%= ENV['DATABASE_PASSWORD'] %>

